### ISSUE TITLE
v1.3.1, alters DSP username

### ISSUE THREAD

**Issue by DocHogan** [mattsemar/dsp-long-arm#2]
Username in top right corner (below "Early Access XXXXXXXX") is changed to "altuser" when dsp-long-arm is enabled.

**Comment by mattsemar** [comment]
Yeah, sorry I let that slip by. Somebody was asking me how to change the name on their game save and since I had the code open I just did it in that mod to test it out. Fast forward to patch day and the scramble to update the mod to work with the new release and I just plain forgot that was still in there.

Can you try the latest version to see if it's still happening?

**Comment by DocHogan** [comment]
It looks good in the latest update, *and* I saw in r2modman that you added a Settings field to customize it...nice touch :)
